config/routes.rb
Rails.application.routes.draw do
resources :posts
root "sessions#index"

#user routes
get "users" => "users#index"
post "users" => "users#create"
get "/signup" => "users#new"


#session routes
get "home" => "sessions#index"
get "login" => "sessions#new"
post "login" => "sessions#create"
delete "logout" => "sessions#destroy"

#post routes
get "posts/" => "posts#index" 
get "posts/:id/earn" => "posts#earned", as: :earn_post
get "users/:id/posts/new" => "posts#new" #as: :new_post 
get "posts/:id" => "posts#show" #, as: :post
post "users/:id/posts/" => "posts#create"
get "posts/:id/edit" => "posts#edit" #, as: :edit_post
post "posts/:id/edit" => "posts#update"
patch "posts/:id" => "posts#update"
delete "posts/:id" => "posts#destroy"

#role routes

get "roles/" => "roles#index"
get "roles/new" => "roles#new", as: :new_role
post "roles/" => "roles#create"

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user

	mount_uploader :image_url, PostImageUploader

end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_and_belongs_to_many :roles
  before_save :format_user_input
  attr_reader :password

    #creating an instance variable and setting it, also ecrypting and authenticating our password
  	def password=(unencrypted_password)
      unless unencrypted_password.empty?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
  	  end
    end


    def authenticate(unencrypted_password)
      if BCrypt::Password.new(self.password_digest) == unencrypted_password
        return self
      else
        return false
      end
    end


    #we are establishing validation requirement for users when they are signing in
    validates :name, presence: true
    validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
    validates :password, presence: true, confirmation: true, length: { in: 6..20 }

    private
    def format_user_input
      self.name = self.name.titleize
      self.email = self.email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception


	helper_method :current_user
	include SessionsHelper

	private
	def current_user
		@current_user ||=User.find(session[:user_id]) if session[:user_id]
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :authorized?, only: [:edit, :update]
	
  def index
		@posts = Post.all
	end

	def earned
		@post = Post.find(params[:id])
    	@post.earned = true
    	@post.save
   		redirect_to posts_path
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@user = current_user
		@post = @user.posts.new

	end

	def create
		@user = current_user
		@post = @user.posts.new(post_params)
			if @post.save
				redirect_to posts_path
			else
				render :new
			end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update_attributes(post_params)
			redirect_to posts_path
		else
			render :edit
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

	private
	def post_params
		params.require(:post).permit(:title, :image_url, :description, :earned, :user)
	end

  	def authorized?
    	unless current_user = Post.find(params[:id])
      		flash[:error] = "You are not authorized to access that page."
      		redirect_to posts_path 
    	end
  	end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

	def index
		@roles = Role.all
	end

	def new
		@role = Role.new
	end

	def create
		@role = Role.new(role_params)

		if @role.save
			redirect_to posts_path
		else
			render :new
		end
    end

    def edit
	end

  private

  def set_role
  	@role = Role.find(params[:id])
  end

  def role_params
    params.require(:role).permit(:name)
  end

	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def index
		
	end

	def new
	
	end

	def create
		user = User.find_by(email: params[:login][:email])

		if user && user.authenticate(params[:login][:password])
			session[:user_id] = user.id.to_s
            flash[:welcome] = "Thanks for logging in, #{user.name}"
			redirect_to posts_path
		else
			flash.now[:error] = "Your email address or password are incorrect."
			render :new
		end
	end

	def destroy
    session.delete(:user_id)
    redirect_to home_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login, except: [:new, :create]
 

    def index
	   	@users = User.all
	  end

	  def new
		  @user = User.new
	  end

	  def create
		  @user = User.new(user_params)

		  if @user.save
		  	 session[:user_id] = @user.id.to_s  #this will allow someone who signs up to be directed to the post index
		  	 flash[:welcome] = "Thanks for signing up, #{@user.name}!"
			 redirect_to posts_path
		  else
			 render :new
		  end
	  end

  private
  def user_params
	 params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access that page!"
      redirect_to home_path
    end
  end

  

end 

app/helpers/application_helper.rb
module ApplicationHelper
	def can_edit(post)
		if (logged_in? && post.user_id == current_user.id)
			return true
		else
			return false
		end
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def logged_in?
		session[:user_id] != nil #this makes it so when we 'logout' the current_user wont be set to a value of nil
	end

end

app/helpers/users_helper.rb
module UsersHelper
	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ErndIt</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:welcome] %>
	<h4 class="bg-success flash"><%= flash[:welcome] %></h4>
<% end %>

<% if flash[:error] %>
	<h4 class="bg-danger flash"><%= flash[:error] %></h4>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<div id="edit-post-controller">

	<h1 class="h1">Edit your Post!</h1>

	<!-- <%= "Earned status: #{@post.earned}"%> -->

	<%= form_for :post do |f| %>


		<div class="edit">
			<section>

				<%= f.label :description %>
				<%= f.text_field :description %>
				
				<br>

				<%= f.label :image_url %>
				<%= f.file_field :image_url %>

				<br>

			</section>
		
		

			<button>
				<%= f.submit "Submit Changes" %>
			</button>
		
			<button><%= link_to "Delete Post", post_path, method: :delete, data: {confirm: "Are you sure you wish to delete this post?"} %></button>

			<% end %>

			<button><%= link_to "Click to Return Home", posts_path %></button>
		</div> <!-- end edit -->

</div> <!-- edit-post-controller -->

app/views/posts/index.html.erb
<div id="main-post-container">
		
	<div class="header">

		<% if logged_in? %>
			<div class="welcome-user">
				<%= "Welcome #{current_user.name}!" %>
			</div>
			
			<div class="user-logout">
				<%= link_to 'Log Out', logout_path, method: :delete %>
			</div>

		<% end %>
	

	
		<div class="h1">
			<h1>WHAT WILL YOU EARN TODAY?</h1>
	    </div> 
	
	</div> <!-- end header -->
   
		

		<div class="body">
			<div class="new-post">
				<%= link_to "Create new Post!", new_post_path %>
			</div>
			
			<ul class="full-post">
				<% @posts.each do |post| %>
					
					<li>
						<div class="username">
							<%= post.user.name %><br>
						</div>

						<div class="post">
							
							<div class="post-image">
								<%= image_tag post.image_url %>
								<div class="<%= "earned-#{post.earned}"%>"><span>ERND IT!</span></div>
							</div>
						
						
							<h3> <%= post.description %> <h3> <br>
							
							
						
							<% if can_edit(post) %>
								<button><%= link_to "EDIT POST", edit_post_path(post) %> </button>
								<button><%= link_to "ERND IT", earn_post_path(post) %></button>
							<% end %>


						</div>
						
					</li>

				<% end %>
			</ul>
		</div> <!-- end body -->
</div> <!-- end main-post-container -->
		
	

app/views/posts/new.html.erb
<div id="new-post-controller">

	<h1 class="h1">Add a Post Here!</h1>

	<%= form_for @post do |f| %>

		<div class="new">
			<p>What is your goal?</p><% f.label :description %>
			<%= f.text_field :description %>
		
		<br>
		<br>

			<p>What would you like to earn?</p><% f.label :image_url %>
			<%= f.file_field :image_url %>

		<br>
		<br>
		

		<button><%= f.submit "Add Post" %></button>

		<button><%= link_to "Back to Home Page", posts_path %></button>

		</div>

	<% end %>


</div> <!-- end new-post-controller -->

app/views/posts/show.html.erb
<div id="comment-container">

	<div class="comment">
		<h1 class="h1"> <%= @post.description %> </h1>

		<br>

		<button><%= link_to "Back to Main Page", posts_path %></button>

	</div>

</div><!-- end comment-container -->

app/views/roles/index.html.erb
<div id="role-index-container">

	<% @roles.each do |role| %>
	      
	    <%= role.name %>
	    <%= link_to 'Show', role %>
	    <%= link_to 'Edit', edit_role_path(role) %>
	    <%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %>
	      
	<% end %>

	<%= link_to 'New Role', new_role_path %>
</div>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= form_for @role, html: {multipart: true} do |f| %>

	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>


	<%= f.submit "Create Role" %>

<% end %>

<%= link_to "Back to the list", roles_path %>

app/views/users/index.html.erb
<% if logged_in? %>

	<%= "Welcome #{current_user.name}!" %>
	<%= link_to 'Log Out', logout_path, method: :delete %>

<% else %>

	<%= link_to "Login", login_path %>
	<%= link_to "Signup", signup_path %> 
  

<% end %>


<h1>This will be the login/welcome page</h1>

app/views/users/new.html.erb
<div class="cover-container">
	<h1 class="h1">Sign up now to enter!</h1>

	<%= form_for @user do |f|  %>

		<% if @user.errors.any? %>
			<div>
				<h4><%= pluralize(@user.errors.count, "error") %> prevented you from signing up for an account:</h4>

				<ul>
					<% @user.errors.full_messages.each do |msg| %>
						<li class="list-group-item list-group-item-danger"><%= msg.downcase %> </li>
					<% end %>
				</ul>
			</div>
		<% end %>



		<div class="login">
			<%= f.label :name %>
			<%= f.text_field :name %>

			<br>
		
			<%= f.label :email %>
			<%= f.text_field :email %>

			<br>
		
			<%= f.label :password %>
			<%= f.password_field :password %>

			<br>
		
	    	<%= f.label :password_confirmation %>
	    	<%= f.password_field :password_confirmation %>
		
	    	

			<button><%= link_to "Login" %></button>

			<button><%= link_to "Go Back", home_path %></button>

		</div>

	<% end %>

</div> <!-- end signup-container -->